# Generated by Django 4.1.2 on 2022-12-28 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50)),
                ("name", models.TextField()),
                ("last_name", models.TextField()),
                ("location", models.CharField(blank=True, max_length=100)),
                ("age", models.IntegerField()),
                ("bio", models.TextField(blank=True)),
            ],
        ),
    ]
