# Generated by Django 4.1.2 on 2022-12-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tour", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="signup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=20)),
                ("firstname", models.CharField(max_length=20)),
                ("lastname", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("password", models.TextField()),
                ("password2", models.TextField()),
            ],
        ),
    ]
