# Generated by Django 4.1.2 on 2023-01-09 08:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("tour", "0003_destination_destinationimages"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="destination",
            name="id",
        ),
        migrations.RemoveField(
            model_name="destinationimages",
            name="id",
        ),
        migrations.RemoveField(
            model_name="signup",
            name="id",
        ),
        migrations.AddField(
            model_name="destination",
            name="created_at",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="destination",
            name="uid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AddField(
            model_name="destination",
            name="updated_at",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="destinationimages",
            name="created_at",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="destinationimages",
            name="uid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AddField(
            model_name="destinationimages",
            name="updated_at",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="signup",
            name="created_at",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="signup",
            name="uid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AddField(
            model_name="signup",
            name="updated_at",
            field=models.DateField(auto_now=True),
        ),
    ]
