# Generated by Django 4.1.2 on 2023-01-09 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tour", "0005_remove_destination_destination_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="destination",
            old_name="destination_details",
            new_name="dest_description",
        ),
        migrations.RenameField(
            model_name="destination",
            old_name="destination_name",
            new_name="dest_name",
        ),
    ]
