# Generated by Django 4.1.2 on 2023-01-09 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "tour",
            "0006_rename_destination_details_destination_dest_description_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="destination",
            old_name="dest_description",
            new_name="destination_description",
        ),
        migrations.RenameField(
            model_name="destination",
            old_name="dest_name",
            new_name="destination_name",
        ),
    ]
