# Generated by Django 4.1.2 on 2023-01-09 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "tour",
            "0007_rename_dest_description_destination_destination_description_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="destination",
            name="destination_images",
            field=models.ImageField(default=1, upload_to="destination"),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="DestinationImages",
        ),
    ]
