# Generated by Django 4.1.2 on 2023-01-10 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tour", "0009_package"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="package_price",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
