# Generated by Django 4.1.2 on 2023-01-10 05:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("tour", "0010_package_package_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="PackageAmenities",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateField(auto_now=True)),
                ("updated_at", models.DateField(auto_now=True)),
                ("package_amenity_name", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="package",
            name="amenities",
            field=models.ManyToManyField(to="tour.packageamenities"),
        ),
    ]
