# Generated by Django 4.1.2 on 2023-01-10 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tour", "0011_packageamenities_package_amenities"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="package",
            name="amenities",
        ),
        migrations.AddField(
            model_name="package",
            name="package_amenity_name",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="PackageAmenities",
        ),
    ]
