# Generated by Django 4.1.2 on 2023-01-10 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tour", "0012_remove_package_amenities_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="package",
            name="package_name",
            field=models.CharField(max_length=50),
        ),
    ]
