# Generated by Django 4.1.2 on 2023-01-10 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tour", "0013_alter_package_package_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="package",
            name="package_image",
        ),
        migrations.AddField(
            model_name="package",
            name="package_images",
            field=models.ImageField(default=1, upload_to="package"),
            preserve_default=False,
        ),
    ]
