# Generated by Django 4.1.2 on 2023-01-17 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tour", "0016_amenities_hotel_hotelimages"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="hotel_images",
            field=models.ImageField(default=1, upload_to="hotels"),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="HotelImages",
        ),
    ]
