# Generated by Django 4.1.2 on 2023-01-18 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tour", "0019_hotelbooking_number_of_person_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hotelbooking",
            name="number_of_person",
        ),
        migrations.RemoveField(
            model_name="hotelbooking",
            name="user_address",
        ),
    ]
