# Generated by Django 4.1.2 on 2023-01-18 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tour", "0021_hotelbooking_user_address_hotelbooking_user_phone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hotelbooking",
            name="user_address",
        ),
        migrations.RemoveField(
            model_name="hotelbooking",
            name="user_phone",
        ),
        migrations.CreateModel(
            name="PackageBooking",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateField(auto_now=True)),
                ("updated_at", models.DateField(auto_now=True)),
                ("user_address", models.CharField(max_length=250)),
                ("user_phone", models.TextField(max_length=10)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("booked_on", models.DateField(auto_now=True)),
                (
                    "booking_type",
                    models.CharField(
                        choices=[("Pre Paid", "Pre Paid"), ("Post Paid", "Post Paid")],
                        max_length=100,
                    ),
                ),
                (
                    "package_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="package_booking",
                        to="tour.package",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_package_booking",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
